### ISSUE TITLE
Tasmota update error

### ISSUE THREAD

**Issue by hugodelaroza** [hassio-addons/addon-tasmoadmin#1]
# Problem/Motivation
When trying to update a tasmotized sonoff frontera my hassio, the device don't update and when trying to checkpoint using browser to reach .bin URL, I recibe permission forbiden messsge

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by hugodelaroza** [comment]
Buenas the way, the addon Is amazing!

**Comment by frenck** [comment]
@hugodelaroza Which version of the add-on are you running?
This should be fixed in 0.1.1

**Comment by hugodelaroza** [comment]
frenck, I updated to 0.1.1 and the file was in the server, but the tasmota didn't updated (tasmota 5.12o), then I tryied with other sonoff woth tasmota 5.12.0 and worked ok

**Comment by frenck** [comment]
The add-on has been updated. Could you please update and try again?

**Comment by hugodelaroza** [comment]
Frenck, te error still continues.
This is the log:

[24-06-2018 16:56:45][GLOBAL] Proceso de Actualización Iniciado
[24-06-2018 16:56:45][ID-4][PASO-1][GLOBAL] Paso 1
[24-06-2018 16:56:45][ID-4][PASO-1][CONEXIÓN] Probando Conexión | INTENTO => 1
[24-06-2018 16:56:45][ID-4][PASO-1][CONEXIÓN] Conexión Exitosa | Versión Actual => 5.12.0o
[24-06-2018 16:56:45][ID-4][PASO-1][URL de OTA] Establecer URL de OTA para Firmware => MINIMAL
[24-06-2018 16:56:45][ID-4][PASO-1][URL de OTA] URL de OTA => http://192.168.0.68:9541/data/firmwares/sonoff-minimal.bin
[24-06-2018 16:56:45][ID-4][PASO-1][URL de OTA] URL de OTA Establecida para Firmware => MINIMAL
[24-06-2018 16:56:45][ID-4][PASO-1][ACTUALIZACIÓN] Iniciando...
[24-06-2018 16:56:45][ID-4][PASO-1][ACTUALIZACIÓN] Iniciada la Actualización de Dispositivo
[24-06-2018 16:56:45][ID-4][PASO-1][COMPROBACIÓN] Esperando la Actualización | Segundos => 60
[24-06-2018 16:57:45][ID-4][PASO-1][COMPROBACIÓN] Actualización Completada!
[24-06-2018 16:57:45][ID-4][PASO-2][GLOBAL] Paso 2
[24-06-2018 16:57:45][ID-4][PASO-2][CONEXIÓN] Probando Conexión | INTENTO => 1
[24-06-2018 16:57:45][ID-4][PASO-2][CONEXIÓN] Conexión Exitosa | Versión Actual => 5.12.0o
[24-06-2018 16:57:45][ID-4][PASO-2][URL de OTA] Establecer URL de OTA para Firmware => NEW FW
[24-06-2018 16:57:45][ID-4][PASO-2][URL de OTA] URL de OTA => http://192.168.0.68:9541/data/firmwares/sonoff-full.bin
[24-06-2018 16:57:45][ID-4][PASO-1][URL de OTA] URL de OTA Establecida para Firmware => NEW FW
[24-06-2018 16:57:45][ID-4][PASO-2][ACTUALIZACIÓN] Iniciando...
[24-06-2018 16:57:45][ID-4][PASO-2][ACTUALIZACIÓN] Iniciada la Actualización de Dispositivo
[24-06-2018 16:57:45][ID-4][PASO-2][COMPROBACIÓN] Esperando la Actualización | Segundos => 60
[24-06-2018 16:58:46][ID-4][PASO-2][Listo] ============= Actualización Completada! =============

After all this, the tasmota version is still 5.12.0o
Some of my sonoff devices where flashed with 64k SPIFFS. Could this be the problem?

**Comment by ascillato** [comment]
Hi,

> Some of my sonoff devices where flashed with 64k SPIFFS. Could this be the problem?

Yes, It has a different memory map.

Sorry, you need to update your sonoff by wire.

**Comment by frenck** [comment]
Closing this issue.
Thank you @ascillato for clearing that up!
